// import axios from 'axios';

// axios
//     .get('fakeapi.com')
//     .then((res) => {
//         console.log(res.data);
//     }) 
//     .catch((err) => {
//         console.error(err);
//     })

// // нужно сделать внутри try catch
// const response = await axios.get('fakeapi.com');
// console.log(response);

// axios({
//     method: 'delete',
//     url: 'fakeapi.com',
//     data: {
//         id: 1,
//         name: 'Joe',
//     },
// })

// const newUser = {
//     id: 120,
//     name: 'Anna',
// }

// axios
//     .post('fakeapi.com', newUser)
//     .then((response) => {
//         console.log(response.data);
//     })
//     .catch((err) => {
//         console.log(err);
//     });


